ordercloud-api/angular-buyer

src/app/myAddresses/myAddresses.js
src/app/myAddresses/templates/myAddresses.tpl.html
src/app/myAddresses/tests/myAddresses.spec.js
src/app/myPayments/myPayments.js
src/app/myPayments/templates/myPayments.tpl.html

Similar to myPayments, we should not be reloading the state when creating, updating, deleting addresses.
Instead, maintain the view model to reflect what happened in the API. Unit Tests updated & passing

My Addresses Performance Updates

---

src/app/styles/pages/_login.less

overall a top positioning was added to the panel element. on smaller screens the border and white background are taken away and the panel element is raised so the input can still be viewed on mobile devices.

CCN-212 login styles for buyer app

---

src/app/common/templates/card.product.tpl.html
src/app/productBrowse/templates/productView.tpl.html
src/app/styles/layout/_catalog-grid.less

Limit characters to product.ID and product.Description bc of overlap and added elipsis if greater than the amount of characters alotted. 
added styling sans flex in anticipation of more CSS styling adjustments in regards to global flex styling etc...

CCN-182, CCN-254

---

src/app/favoriteProducts/favoriteProducts.js
src/app/favoriteProducts/tests/favoriteProducts.spec.js

update unit test
refactor code as result of unit test

[OC-2058] Update Unit test

---

bower.json
src/app/common/filters/oc-shipment-tracking/oc-shipment-tracking.js
src/app/myOrders/payments/js/orderPayments.service.js
src/app/myOrders/shipments/js/orderShipments.config.js
src/app/myOrders/shipments/js/orderShipments.controller.js
src/app/myOrders/shipments/js/orderShipments.service.js
src/app/myOrders/shipments/templates/orderShipments.html

Adding functionality for new Me.ListShipmentItems endpoint. Also updating the OrderCloudSDK version to include that method.

My Orders Shipment Items update

---

src/app/app.controller.js
src/app/common/directives/oc-if-roles/oc-if-roles.js
src/app/common/directives/oc-readonly-roles/oc-readonly-roles.js
src/app/common/services/oc-roles/oc-roles.js
src/app/login/js/login.controller.js
src/app/login/js/login.service.js

- Change ocRolesService to ocRoles
- Change ocRoles provider to $ocRoles
- Remove ocRoles.Remove() functionality
- Add object notation example
- Update ocRoles service logic

ocRoles refactor

---

src/app/productBrowse/js/productBrowse.controller.js

object needed to be stringified by
ocParameters.Create
OC-2153 #49

bugFix: refine by favorite products causes error

---

src/app/favoriteProducts/js/favoriteProduct.controller.js
src/app/favoriteProducts/js/favoriteProducts.controller.js
src/app/favoriteProducts/tests/favoriteProducts.spec.js
src/global.spec.js

- fixes old unit tests
- adds new tests for FavoriteProductsCtrl

update unit tests for favoriteProducts

---

src/app/base/js/base.controller.js
src/app/productSearch/js/productSearch.component.js
src/app/productSearch/js/productSearch.config.js
src/app/productSearch/js/productSearch.modal.controller.js

- cause: new sdk was expecting search instead of searchTerm param

Fix search - not filtering on hard enter

---

src/app/common/services/oc-refresh-token/oc-refresh-token.js
src/app/common/services/oc-state-loading/oc-state-loading.js

chore: check token exists before making any calls

---

src/app/productDetail/js/specForm.directive.js

fix: remove catalogid from Me.ListSpecs call to display specs on product

F51-166 No Spec Form on Product Detail Page

---

src/app/checkout/payment/directives/js/creditCard.controller.js
src/app/checkout/payment/directives/js/payment.controller.js
src/app/checkout/payment/directives/js/purchaseOrder.controller.js
src/app/checkout/payment/directives/js/spendingAccount.controller.js
src/app/checkout/payment/directives/templates/payment.html
src/app/checkout/payment/directives/templates/purchaseOrder.html
src/app/checkout/payment/directives/templates/selectPaymentAccount.modal.html
src/app/checkout/payment/js/payment.controller.js
src/app/checkout/payment/js/payment.service.js
src/app/checkout/payment/templates/checkout.payment.html

Updated purchase order payment directive so that it contains the "Save" button.
Moved the event "OCPaymentUpdated" broadcast into the payments.service.js (Save method)
Added a hidden input element that is required if payment.Type == CreditCard

F51-148 Require billing address on CC payments

---

src/app/categoryBrowse/templates/categoryBrowse.html
src/app/favoriteProducts/templates/favoriteProducts.html
src/app/productBrowse/README.md

- Use directive on Category Browse
- Use directive on Favorite Products

F51-178 Product Card fixes

---

src/app/myOrders/orders/tests/orders.spec.js
src/app/productBrowse/tests/productBrowse.spec.js

refactor unit test for productBrowse component
- also remove unnecessary spy from myOrders - orders unit test

F51-120 productBrowse unit test

---

src/app/favoriteOrders/js/favoriteOrders.component.js
src/app/favoriteOrders/tests/favoriteOrder.spec.js

refactor: unit test for favoriteOrder component

F51-207 favoriteOrder unit test

---

src/app/login/js/login.config.js
src/app/login/js/login.controller.js
src/app/login/tests/login.spec.js

* the forgot your password flow was hitting a
deprecated endpoint.
* updated $stateParams from token to validationCode
for clarity. token was what was previously being
passed in, but new method now uses validation code
F51-240

update forgot your password for post-bbc endpoint

---

src/app/common/directives/oc-product-card/oc-product-card.js

fix: update mini cart badge quantity count after adding products from product browse view

F51-257 - Cart badge count is displaying incorrectly

---

gulp.config.js

this keeps it consistent with the other constants
in app.constants.json
F51-272

expose anonymous constant as heroku variable

---

src/app/account/js/changePassword.modal.controller.js
src/app/account/js/confirmPassword.modal.controller.js
src/app/account/templates/changePassword.modal.html
src/app/common/config/error-handling/error-handling.js
src/app/login/js/login.controller.js
src/app/register/js/register.controller.js

- Update change password pattern
- Encode password before sending to SDK

F51-125 Password invalid messaging

---

src/app/common/directives/oc-reorder/js/oc-reorder.directive.js
src/app/common/directives/oc-reorder/js/oc-reorder.modal.controller.js
src/app/common/directives/oc-reorder/js/oc-reorder.modal.service.js
src/app/common/directives/oc-reorder/tests/oc-reorder.spec.js
src/global.spec.js

per feedback from team
F51-151

refactor: rename ocReorderModal to ocReorder

---

bower.json
gulp/build/styles.js
gulp/compile/app-css.js
src/app/app.constants.json
src/app/app.module.js
src/app/common/directives/oc-related-products/oc-related-products.html
src/app/common/directives/oc-related-products/oc-related-products.js
src/app/common/services/oc-related-products/oc-related-products.js
src/app/common/services/oc-related-products/oc-related-products.spec.js
src/app/productDetail/templates/productDetail.html
src/app/styles/components/_related-products.less
src/app/styles/components/_slick.less
src/app/styles/components/glob.less

When in a product detail view, if `Product.xp.RelatedProducts` has an array of Product IDs, those products are displayed in a carousel.

F51-28 Related Products Directive

---

src/app/common/services/oc-payment/oc-payment.js
src/app/login/js/login.controller.js

* Add exception handler for create payment function in oc payments service
* Fix for $window is not defined error on login

F51-258 - checkout: payment select modal

---

src/app/categoryBrowse/js/categoryBrowse.config.js
src/app/categoryBrowse/js/categoryBrowse.controller.js
src/app/categoryBrowse/tests/categoryBrowse.spec.js
src/app/login/tests/login.spec.js
src/global.spec.js

caused by a change in the way we handle forgot
password
F51-318

test: fix broken tests for login component

---

src/app/favoriteProducts/js/favoriteProducts.directive.js
src/app/favoriteProducts/tests/favoriteProducts.spec.js

- slight refactor to make directive more testable
- update unit tests for directive as it is now an attribute directive

update ocFavoriteProduct unit tests

---

src/app/productQuickView/tests/productQuickView.spec.js
src/global.spec.js

functions slightly difference since it is now
an attribute directive
F51-333

test: update ocProductQuickView tests

---

src/app/categoryBrowse/templates/categoryBrowse.html
src/app/common/directives/oc-product-card/oc-product-card.html
src/app/common/directives/oc-product-card/oc-product-card.js
src/app/favoriteProducts/js/favoriteProducts.config.js
src/app/favoriteProducts/js/favoriteProducts.controller.js
src/app/favoriteProducts/js/favoriteProducts.directive.js
src/app/favoriteProducts/js/favoriteProducts.service.js
src/app/favoriteProducts/templates/favoriteProducts.html
src/app/favoriteProducts/tests/favoriteProducts.spec.js
src/app/productBrowse/js/productBrowse.config.js
src/app/productBrowse/js/productBrowse.controller.js
src/app/productBrowse/templates/productView.html
src/app/productDetail/templates/productDetail.html
src/app/productQuickView/templates/productQuickView.modal.html
src/app/styles/components/_buttons.less
src/app/styles/components/_catalog-card.less
src/app/styles/utils/_variables.less

Bug Fix:
F51-409 - Account for products without pricing
F51-428 - Favorite products directive cleanup (see commit 02900fc)
Design changes:
- Update category browse & favorite products product list so that it displays the same as productBrowse

F51-428 & F51-409

---

src/app/common/services/oc-confirm/tests/oc-confirm.spec.js

refactor: fix failing unit test for ocConfirm unit test
F51-312

F51-312 - ocConfirm unit test

---

server.js
src/app/home/js/home.controller.js
src/app/home/templates/home.html

- Change img src from Src to URL for consistency

F51-242 Static Image Slider update

---

src/app/common/directives/oc-payment/oc-payment.html
src/app/common/services/oc-authnet/oc-authnet.js
src/app/myPayments/templates/myPayments.html

also fix for month not displaying correctly by adding UTC timezone to date filter

Authorize and Capture method for ocAuth service

---

src/app/login/js/login.controller.js

this is a buyer application so only buyer users should be able to sign in. Many features are broken for seller users.

warn if attempting to sign in as a seller user
